export const actionTypes = {
  TURN_ON_LOADING: "TURN_ON_LOADING",
  TURN_OFF_LOADING: "TURN_OFF_LOADING",

  // COURSES
  SAVE_COURSE_LIST: "SAVE_COURSE_LIST",
  SAVE_COURSE_CATEGORY_LIST: "SAVE_COURSE_CATEGORY_LIST",
  SAVE_COURSE_DETAIL: "SAVE_COURSE_DETAIL",

  // USER
  SAVE_USER: "SAVE_USER",
  LOG_OUT: "LOG_OUT",
};
