export const sagaTypes = {
  GET_COURSE_LIST_SAGA: "GET_COURSE_LIST_SAGA",
  GET_COURSE_CATEGORY_LIST_SAGA: "GET_COURSE_CATEGORY_LIST_SAGA",
  GET_COURSE_BY_CATEGORY_SAGA: "GET_COURSE_BY_CATEGORY_SAGA",
  GET_COURSE_DETAIL_SAGA: "GET_COURSE_DETAIL_SAGA",

  // USER
  SIGN_IN_SAGA: "SIGN_IN_SAGA",
  SIGN_UP_SAGA: "SIGN_UP_SAGA",
  GET_USER_DETAIL_SAGA: "GET_USER_DETAIL_SAGA",
};
